#
#  Copyright (c) 2025 Fraunhofer Institute for Energy Economics and Energy System Technology (IEE)
#
#  This program and the accompanying materials are made available under the
#  terms of the Apache License, Version 2.0 which is available at
#  https://www.apache.org/licenses/LICENSE-2.0
#
#  SPDX-License-Identifier: Apache-2.0
#
#  Contributors:
#       Fraunhofer IEE - initial API and implementation
#
#

# Global settings
title: Re4DE Open API Specs
description: Open API Specs for the Re4DE Stack. Also include the API Specs from the EDCs.
show_downloads: false

domain: re4de.github.io
url: "https://re4de.github.io"
baseurl: "/open-api/"

# Build settings
remote_theme: pages-themes/primer@v0.6.0
plugins:
  - jekyll-remote-theme

# https://github.com/github/pages-gem/issues/399#issuecomment-301827749
# When running locally, we run into the following error —
# GitHub Metadata: No GitHub API authentication could be found. Some fields may be missing or have incorrect data.
# adding this avoids it
github: [metadata]